blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (BlogPostCreateView, BlogPostListView, BlogPostDetailView,
                        BlogPostUpdateView, BlogPostDeleteView, toggle_publication)

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('', BlogPostListView.as_view(), name='list'),
    path('<int:pk>/update/', BlogPostUpdateView.as_view(), name='update'),
    path('<int:pk>/view/', cache_page(60)(BlogPostDetailView.as_view()), name='view'),
    path('<int:pk>/delete/', BlogPostDeleteView.as_view(), name='delete'),
    path('<int:pk>/publication/', toggle_publication, name='toggle_publication'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('mailing.urls', 'mailing'))),
    path('client/', include(('client.urls', 'client'))),
    path('users/', include(('users.urls', 'users'))),
    path('blog/', include(('blog.urls', 'blog'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import MailingMessageListView, MailingMessageCreateView, MailingMessageDetailView, \
    MailingMessageUpdateView, MailingMessageDeleteView, MailingSettingsListView, MailingSettingsCreateView, \
    MailingSettingsDetailView, MailingSettingsUpdateView, MailingSettingsDeleteView, HomeTemplateView, \
    MailingStatusListView, MailingStatusDetailView

app_name = MailingConfig.name

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('list', MailingMessageListView.as_view(), name='list'),
    path('create/', MailingMessageCreateView.as_view(), name='create'),
    path('<int:pk>/', cache_page(60)(MailingMessageDetailView.as_view()), name='view'),
    path('<int:pk>/update/', MailingMessageUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', MailingMessageDeleteView.as_view(), name='delete'),
    path('settings/', MailingSettingsListView.as_view(), name='settings_list'),
    path('settings/create/', MailingSettingsCreateView.as_view(), name='settings_create'),
    path('settings/<int:pk>/', cache_page(60)(MailingSettingsDetailView.as_view()), name='settings_view'),
    path('settings/<int:pk>/update/', MailingSettingsUpdateView.as_view(), name='settings_edit'),
    path('settings/<int:pk>/delete/', MailingSettingsDeleteView.as_view(), name='settings_delete'),
    path('status_list', MailingStatusListView.as_view(), name='mailing_status_list'),
    path('status_detail/<int:pk>', MailingStatusDetailView.as_view(), name='mailing_status_detail'),
]

mailing/models.py
from django.conf import settings
from django.db import models

from client.models import Client
from users.models import User

NULLABLE = {"null": True, "blank": True}
FREQUENCY_CHOICES = [
    ("Daily", "Раз в день"),
    ("Weekly", "Раз в неделю"),
    ("Monthly", "раз в месяц"),
]
STATUS_OF_NEWSLETTER = [
    ("Create", "Создана"),
    ("Started", "Запущена"),
    ("Done", "Завершена"),
]
LOGS_STATUS_CHOICES = [
    ("Success", "Успешно"),
    ("Fail", "Не успешно"),
]


class MailingMessage(models.Model):
    """Модель для сообщения"""

    title = models.CharField(max_length=100, verbose_name="Тема письма")
    content = models.TextField(verbose_name="Тело письма")
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Автор", **NULLABLE
    )

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

    def __str__(self):
        return self.title


class MailingSettings(models.Model):
    """Модель для рассылки"""

    first_datetime = models.DateTimeField(
        auto_now_add=True, verbose_name="Начало рассылки"
    )
    next_datetime = models.DateTimeField(verbose_name="Следующая дата отправки", **NULLABLE)
    end_time = models.DateTimeField(verbose_name="Конец рассылки", **NULLABLE)
    sending = models.CharField(
        max_length=50, choices=FREQUENCY_CHOICES, verbose_name="Период рассылки"
    )
    message = models.ForeignKey(
        MailingMessage, on_delete=models.CASCADE, verbose_name="Сообщение"
    )
    setting_status = models.CharField(
        max_length=50,
        choices=STATUS_OF_NEWSLETTER,
        verbose_name="Статус рассылки",
        default="Create",
    )
    clients = models.ManyToManyField(Client, verbose_name="Получатели")
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Автор", **NULLABLE
    )

    class Meta:
        verbose_name = "Настройка рассылки"
        verbose_name_plural = "Настройки рассылки"
        permissions = [
            ("can_change_setting_status", "Может отключать рассылку"),
        ]

    def __str__(self):
        return (
            f"{self.message} отправляется каждый {self.sending} с {self.first_datetime}"
        )


class MailingStatus(models.Model):
    """Модель для статуса рассылки"""

    last_datetime = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время последней рассылки"
    )
    status = models.CharField(
        max_length=50,
        choices=LOGS_STATUS_CHOICES,
        default="",
        verbose_name="Статус попытки",
    )
    mailing_response = models.TextField(verbose_name="Ответ почтового сервера")
    mailing = models.ForeignKey(
        MailingSettings, on_delete=models.CASCADE, verbose_name="Рассылка"
    )
    client = models.ForeignKey(
        Client, on_delete=models.CASCADE, verbose_name="Клиент рассылки", **NULLABLE
    )
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Автор", **NULLABLE
    )

    class Meta:
        verbose_name = "Статус отправки"
        verbose_name_plural = "Статусы отправки"

    def __str__(self):
        return f"{self.status} в {self.last_datetime}, ответ сервера: {self.mailing_response}"

mailing/forms.py
from django import forms

from client.models import Client
from mailing.models import MailingSettings, MailingMessage
from users.forms import StileFormMixin


class MailingSettingsForm(StileFormMixin, forms.ModelForm):
    """Форма для создания статьи"""
    def __init__(self, *args, **kwargs):
        """Разрешает выводить только тех клиентов и сообщения,
        которые принадлежат пользователю"""
        self.request = kwargs.pop('request')
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(owner=user)
        self.fields['message'].queryset = MailingMessage.objects.filter(owner=user)

    class Meta:
        model = MailingSettings
        fields = ('end_time', 'sending', 'message', 'setting_status', 'clients',)


class MailingSettingsModeratorForm(StileFormMixin, forms.ModelForm):
    """Форма для менеджера"""
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        user = self.request.user
        super().__init__(*args, **kwargs)

    class Meta:
        model = MailingSettings
        fields = ('setting_status',)


class MailingMessageForm(StileFormMixin, forms.ModelForm):
    """Форма для создания статьи"""
    class Meta:
        model = MailingMessage
        fields = ('title', 'content',)

mailing/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import DeleteView, DetailView, ListView, UpdateView, CreateView, TemplateView

from blog.models import BlogPost
from client.models import Client
from mailing.forms import MailingSettingsModeratorForm, MailingSettingsForm, MailingMessageForm
from mailing.models import MailingSettings, MailingMessage, MailingStatus
from mailing.services import get_mailings_from_cache, get_messages_from_cache


class HomeTemplateView(TemplateView):
    """Контроллер для главной страницы"""
    template_name = 'mailing/home.html'

    def get_context_data(self, **kwargs):
        mailing_count = MailingMessage.objects.count()
        is_active_count = MailingSettings.objects.filter(setting_status='Started').count()
        clients_count = Client.objects.distinct('email').count()
        blog_list = list(BlogPost.objects.all())
        random.shuffle(blog_list)
        random_blog_list = blog_list[:3]
        mailings = MailingSettings.objects.all()
        context_data = {
            'mailing_count': mailing_count,
            'is_active_count': is_active_count,
            'clients_count': clients_count,
            'random_blog_list': random_blog_list,
            'mailings': mailings,
        }
        return context_data


class MailingMessageCreateView(LoginRequiredMixin, CreateView):
    model = MailingMessage
    fields = ['title', 'content']
    success_url = reverse_lazy('mailing:list')

    def form_valid(self, form):
        mailingmessage = form.save()
        mailingmessage.owner = self.request.user
        mailingmessage.save()
        return super().form_valid(form)


class MailingMessageUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingMessage
    fields = ['title', 'content']
    success_url = reverse_lazy('mailing:list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return MailingMessageForm
        raise PermissionDenied


class MailingMessageDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingMessage
    success_url = reverse_lazy('mailing:list')


class MailingMessageListView(LoginRequiredMixin, ListView):
    model = MailingMessage

    def get_queryset(self):
        queryset = get_messages_from_cache()
        if not (self.request.user.is_superuser or self.request.user.has_perm('mailing.view_mailingmessage')):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailingMessageDetailView(LoginRequiredMixin, DetailView):
    model = MailingMessage


class MailingSettingsCreateView(LoginRequiredMixin, CreateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('mailing:settings_list')

    def form_valid(self, form):
        mailing = form.save()
        mailing.next_datetime = mailing.first_datetime
        mailing.owner = self.request.user
        mailing.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class MailingSettingsUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('mailing:settings_list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return MailingSettingsForm
        if user.has_perm('mailing.can_change_setting_status'):
            return MailingSettingsModeratorForm
        raise PermissionDenied

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class MailingSettingsListView(LoginRequiredMixin, ListView):
    model = MailingSettings

    def get_queryset(self):
        queryset = get_mailings_from_cache()
        if not (self.request.user.is_superuser or self.request.user.has_perm('mailing.can_change_setting_status')):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailingSettingsDetailView(LoginRequiredMixin, DetailView):
    model = MailingSettings


class MailingSettingsDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingSettings
    success_url = reverse_lazy('mailing:settings_list')


class MailingStatusListView(LoginRequiredMixin, ListView):
    model = MailingStatus

    def get_queryset(self):
        queryset = MailingStatus.objects.all()
        if not (self.request.user.is_superuser or self.request.user.has_perm('mailing.can_change_setting_status')):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailingStatusDetailView(LoginRequiredMixin, DetailView):
    model = MailingStatus

mailing/templates/mailing/home.html
{% extends 'client/base.html' %}
{% block content %}
<div class="container">
    <main>
        <div class="row">
            {% if user.is_authenticated or perms.mailing.can_change_setting_status or perms.mailing.add_mailingmessage %}
            <div class="col-sm-6 mb-3 mb-sm-0">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Мои рассылки</h5>
                        <a href="{% url 'mailing:settings_list' %}" class="btn btn-primary">Перейти</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Мои клиенты</h5>
                        <a href="{% url 'client:list' %}" class="btn btn-primary">Перейти</a>
                    </div>
                </div>
            </div>
            {% endif %}
            {% if user.is_authenticated or perms.mailing.add_mailingmessage %}
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Мои сообщения</h5>
                        <a href="{% url 'mailing:list' %}" class="btn btn-primary">Перейти</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Отчет проведенных рассылок</h5>
                        <a href="{% url 'mailing:mailing_status_list' %}" class="btn btn-primary">Перейти</a>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
        <div class="py-5 text-center">
            <h1>Добро пожаловать в сервис рассылок!</h1>
            <h2>Email-рассылки могут решать следующие задачи:</h2>
            <p class="lead">- Собрать базу клиентов.
                - Информировать о новых товарах и услугах.
                - Предложить акции, скидки, специальные предложения.
                - Рассказать о новостях, выходе нового контента на сайте.
                - Собрать обратную связь от клиентов.
            </p>
            <p class="lead">Здесь вы можете создать и настроить отправку рассылок для информирования и привлечения
                клиентов.</p>
            {% if perms.mailing.add_mailingsettings %}
            <p class="lead">
                <a href="{% url 'mailing:create' %}" class="me-3 py-2 link-body-emphasis text-decoration-none">Создать
                    рассылку</a>
            </p>
            {% endif %}
            <br>
            <div class="row">
                <div class="col-6 text-sm-start">
                    <li>Количество рассылок на сайте - {{mailing_count}}</li>
                    <li>Количество активных рассылок - {{is_active_count}}</li>
                    <li>Количество клиентов - {{clients_count}}</li>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-12 text-sm-start">
                    <a class="nav-link active" href="{% url 'blog:list' %}">Зайдите в наш блог, это только часть
                        статей</a>
                    {% for article in random_blog_list %}
                    <h1><a href="{% url 'blog:view' article.pk %}" class="nav-link px-2 text-body-dark">{{ article.title }}</a></h1>
                    <p>{{article.body}}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

mailing/templates/mailing/mailingmessage_confirm_delete.html
{% extends 'client/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Хотите удалить сообщение? {{ object.title }}?</p>
                    <button type="submit" class="btn btn-success">Удалить</button>
                    <a class="btn btn-primary" href="{% url 'mailing:list' %}" role="button">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailingmessage_detail.html
{% extends 'client/base.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-9">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <h5>{{ object.content }}</h5>
                    <p>{{ object.clients }}</p>
                    <a class="btn btn-warning" href="{% url 'mailing:edit' object.pk %}" role="button">Изменить</a>
                    <a class="btn btn-primary" href="{% url 'mailing:list' %}" role="button">Назад</a>
                    <a class="btn btn-danger" href="{% url 'mailing:delete' object.pk %}" role="button">Удалить</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailingmessage_form.html
{% extends 'client/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body">
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">
                        {% if object %}
                        Изменить сообщение
                        {% else %}
                        Добавить сообщение
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailingmessage_list.html
{% extends 'client/base.html' %}

{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h2 class="display-4 fw-normal text-body-emphasis">Мои сообщения</h2>
    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'mailing:create' %}">Создать
        сообщение</a>
</div>
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for mail in object_list %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h2 class="my-0 fw-normal">{{ mail.title }}</h2>
            </div>
            <div class="card-body">
                <p class="card-title pricing-card-title">{{ mail.content | slice:":100" }}</p>
                <p class="card-title pricing-card-title">Автор: {{ mail.owner }}</p>
                <a class="btn btn-primary" href="{% url 'mailing:view' mail.pk %}" role="button">Просмотреть</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

mailing/templates/mailing/mailingsettings_confirm_delete.html
{% extends 'client/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Хотите удалить рассылку? {{ object.title }}?</p>
                    <button type="submit" class="btn btn-success">Удалить</button>
                    <a class="btn btn-primary" href="{% url 'mailing:settings_list' %}" role="button">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailingsettings_detail.html
{% extends 'client/base.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-9">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal"><h5>Создана: {{ object.first_datetime }}</h5></h4>
                </div>
                <div class="card-body">
                    {% for item in object.clients.all %}
                    <p>Для: {{ item }}</p>
                    <p class="card-title pricing-card-title">Периодичность: {{ object.sending }}</p>
                    <p class="card-title pricing-card-title">Статус: {{ object.setting_status }}</p>
                    <p class="card-title pricing-card-title">Следующий запуск: {{ object.next_datetime }}</p>
                    <p class="card-title pricing-card-title">Завершится: {{ object.end_time }}</p>
                    <p class="card-title pricing-card-title">Автор: {{ object.owner }}</p>
                    {% endfor %}
                    <a class="btn btn-warning" href="{% url 'mailing:settings_edit' object.pk %}"
                       role="button">Изменить</a>
                    <a class="btn btn-primary" href="{% url 'mailing:settings_list' %}" role="button">Назад</a>
                    {% if user == object.owner or user.is_superuser %}
                    <a class="btn btn-danger" href="{% url 'mailing:settings_delete' object.pk %}"
                       role="button">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailingsettings_form.html
{% extends 'client/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body">
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">
                        {% if object %}
                        Изменить настройки рассылки
                        {% else %}
                        Добавить рассылку
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailingsettings_list.html
{% extends 'client/base.html' %}

{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h2 class="display-4 fw-normal text-body-emphasis">Мои рассылки</h2>
    {% if user.is_authenticated %}
    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'mailing:settings_create' %}">Создать
        рассылку</a>
    {% endif %}
</div>
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for object in object_list %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h2 class="my-0 fw-normal">Создана: {{ object.first_datetime }}</h2>
            </div>
            <div class="card-body">
                {% for item in object.clients.all %}
                <p class="card-title pricing-card-title">Для: {{ item }}</p>
                {% endfor %}
                <p class="card-title pricing-card-title">Периодичность: {{ object.sending }}</p>
                <p class="card-title pricing-card-title">Статус: {{ object.setting_status }}</p>
                <p class="card-title pricing-card-title">Завершится: {{ object.end_time }}</p>
                <p class="card-title pricing-card-title">Автор: {{ object.owner }}</p>
                <a class="btn btn-primary" href="{% url 'mailing:settings_view' object.pk %}"
                   role="button">Просмотреть</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

mailing/templates/mailing/mailingstatus_detail.html
{% extends 'client/base.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-9">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.last_datetime }}</h4>
                </div>
                <div class="card-body">
                    <h5>Статус: {{ object.status }}</h5>
                    <h5>Ответ почтового сервера: {{ object.mailing_response }}</h5>
                    <h5>Рассылка: {{ object.mailing }}</h5>
                    <h5>Автор: {{ object.owner }}</h5>
                    <a class="btn btn-success" href="{% url 'mailing:mailing_status_list' %}"
                       role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailingstatus_list.html
{% extends 'client/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <br/>
    <h4>Отчет по вашим рассылкам</h4>
</div>
<div class="row">
    <div class="col-12">
        <div class="table-responsive small">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Рассылка</th>
                    <th scope="col">Дата и время последней рассылки</th>
                    <th scope="col">Cтатус</th>
                    <th scope="col">Ответ почтового сервера</th>
                </tr>
                </thead>
                <tbody>
                {% for status in object_list %}
                <tr>
                    <td>{{status.pk}}</td>
                    <td>{{status.mailing}}</td>
                    <td><a href="{% url 'mailing:mailing_status_detail' status.pk %}" class="nav-link px-2 text-body-dark">{{ status.last_datetime }}</a></td>
                    <td>{{status.status}}</td>
                    <td>{{status.mailing_response}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}