blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (BlogPostCreateView, BlogPostListView, BlogPostDetailView,
                        BlogPostUpdateView, BlogPostDeleteView, toggle_publication)

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('', BlogPostListView.as_view(), name='list'),
    path('<int:pk>/update/', BlogPostUpdateView.as_view(), name='update'),
    path('<int:pk>/view/', cache_page(60)(BlogPostDetailView.as_view()), name='view'),
    path('<int:pk>/delete/', BlogPostDeleteView.as_view(), name='delete'),
    path('<int:pk>/publication/', toggle_publication, name='toggle_publication'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('mailing.urls', 'mailing'))),
    path('client/', include(('client.urls', 'client'))),
    path('users/', include(('users.urls', 'users'))),
    path('blog/', include(('blog.urls', 'blog'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class BlogPost(models.Model):
    """Модель для поста в блоге"""

    title = models.CharField(max_length=200, verbose_name="Заголовок")
    slug = models.CharField(
        max_length=200, unique=True, verbose_name="Slug", **NULLABLE
    )
    body = models.TextField(verbose_name="Содержимое")
    image = models.ImageField(verbose_name="Превью", upload_to="blog/", **NULLABLE)
    created = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)
    published = models.BooleanField(verbose_name="Признак публикации", default=True)
    views = models.IntegerField(
        verbose_name="Количество просмотров", editable=False, default=0
    )
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name="Создан пользователем",
        **NULLABLE,
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

blog/forms.py
from django import forms

from blog.models import BlogPost
from users.forms import StileFormMixin


class BlogPostForm(StileFormMixin, forms.ModelForm):
    """Форма для создания статьи"""
    class Meta:
        model = BlogPost
        fields = ('title', 'body', 'image',)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import BlogPostForm
from blog.models import BlogPost


class BlogPostListView(ListView):
    model = BlogPost


class BlogPostDetailView(DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save(update_fields=['views'])
        return self.object


class BlogPostCreateView(LoginRequiredMixin, CreateView):
    model = BlogPost
    fields = ('title', 'body', 'image',)
    success_url = reverse_lazy("blog:list")

    def form_valid(self, form):
        if form.is_valid:
            new_object = form.save(commit=False)
            new_object.slug = slugify(new_object.title)
            new_object.user = self.request.user
            new_object.save()
            return super().form_valid(form)


class BlogPostUpdateView(LoginRequiredMixin, UpdateView):
    model = BlogPost
    form_class = BlogPostForm

    def form_valid(self, form):
        if form.is_valid:
            new_object = form.save(commit=False)
            new_object.slug = slugify(new_object.title)
            new_object.user = self.request.user
            new_object.save()
            return super().form_valid(form)

    def get_success_url(self):
        return reverse("blog:view", args=[self.kwargs.get("pk")])


class BlogPostDeleteView(LoginRequiredMixin, DeleteView):
    model = BlogPost
    success_url = reverse_lazy("blog:list")


def toggle_publication(request, pk):
    blogpost_item = get_object_or_404(BlogPost, pk=pk)
    if blogpost_item.published:
        blogpost_item.published = False
    else:
        blogpost_item.published = True

    blogpost_item.save()

    return redirect(reverse("blog:list"))

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'client/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно хотите удалить {{ object.title }}?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">Удалить</button>
                    <a class="btn btn-primary" href="{% url 'blog:list' %}">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_detail.html
<!doctype html>
{% extends 'client/base.html' %}
{% block content %}
{% load my_tags %}
<div class="row text-center">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-6">
                    <img class="card-img-top" src="{{ object.image | media_filter }}">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.title }} ({{ object.slug }})</h5>
                        <p class="card-text">{{ object.body }}</p>
                        <p class="card-text"><small class="text-body-secondary">Дата создания:
                            {{ object.created }}</small></p>
                        <p class="card-text"><small class="text-body-secondary">Количество просмотров:
                            {{ object.views }}</small></p>
                        <a class="btn btn-info" href="{% url 'blog:list' %}">Вернуться к списку публикаций</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'client/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Редактировать запись
                        {% else %}
                        Добавить запись
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_list.html
<!doctype html>
{% extends 'client/base.html' %}
{% block content %}
{% load my_tags %}
{% if perms.blog.add_blogpost %}
<p>
    <a class="btn btn-primary" href="{% url 'blog:create' %}">Добавить запись</a>
</p>
{% endif %}
<div class="row text-center">
    <div class="row row-cols-1 row-cols-md-3 g-6">
        {% for post in object_list %}
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-12">
                    <img src="{{ post.image | media_filter }}" class="card-img-top">
                </div>
                <div class="col-md-12">
                    <div class="card-body">
                        {% if post.published %}
                        <h5 class="card-title">{{ post|title }}</h5>
                        {% else %}
                        <h5 class="text-muted">{{ post|title }}</h5>
                        {% endif %}
                        <p class="card-text">{{ post.body|slice:100 }}</p>
                        <p class="card-text"><small class="text-body-secondary">Дата создания
                            {{ post.created }}</small></p>
                        <p class="card-text"><small class="text-body-secondary">Количество просмотров:
                            {{ post.views }}</small></p>
                        <p class="card-title pricing-card-title">Автор: {{ post.user }}</p>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group" role="group" aria-label="Группа маленьких кнопок">
                            <a href="{% url 'blog:view' post.pk %}" type="button" class="btn btn-danger">Посмотреть</a>
                            {% if perms.blog.change_blogpost or user.is_superuser%}
                            <a href="{% url 'blog:update' post.pk %}" type="button" class="btn btn-warning">Изменить</a>
                            {% endif %}
                            {% if perms.blog.delete_blogpost or user.is_superuser%}
                            <a href="{% url 'blog:delete' post.pk %}" type="button" class="btn btn-success">Удалить</a>
                            {% if post.published %}
                            <a class="btn btn-light" href="{% url 'blog:toggle_publication' post.pk %}">Отменить
                                публикацию</a>
                            {% else %}
                            <a class="btn btn-info" href="{% url 'blog:toggle_publication' post.pk %}">Опубликовать</a>
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}